name: Azure Function Deploy With CICD
on:
  workflow_dispatch:
 
permissions:
  id-token: write
  contents: read
 
jobs: 
  deploy-functions:
    runs-on: ubuntu-latest
 
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
 
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
          architecture: x64
 
      - name: Install required Python modules
        run: |
          cd ./AzureFunctionDeploy  # Navigate to AzureFunctionDeploy directory
          python -m pip install --upgrade pip
          pip install --target="./.python_packages/lib/site-packages" -r requirements.txt
 
      - name: Zip the Azure Function Deploy folder
        run: |
          cd AzureFunctionDeploy  # Navigate to AzureFunctionDeploy directory
          zip -r ../AzureFunctionDeploy.zip ./*
 
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
 
      - name: Run az commands
        run: |
          az account show
          az group list
 
      - name: Deploy Azure Function App
        run: |
          az functionapp deployment source config-zip \
            --resource-group minalmandloi \
            --name my-minu-function \
            --src AzureFunctionDeploy.zip
